version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
